/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import java.awt.Color;
import logica.Operaciones;

/**
 *
 * @author Estudiantes
 */
public class CalculadoraGUI extends javax.swing.JFrame {
    Operaciones op = new Operaciones();
    
    int resta1;
    int suma1;
    int multiplicacion1;
    int division1;
    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NUM2 = new javax.swing.JLabel();
        NUM6 = new javax.swing.JLabel();
        NUM9 = new javax.swing.JLabel();
        NUM3 = new javax.swing.JLabel();
        borrar = new javax.swing.JLabel();
        pantalla = new javax.swing.JLabel();
        division = new javax.swing.JLabel();
        subpantalla = new javax.swing.JLabel();
        NUM10 = new javax.swing.JLabel();
        NUM1 = new javax.swing.JLabel();
        igual = new javax.swing.JLabel();
        NUM4 = new javax.swing.JLabel();
        suma = new javax.swing.JLabel();
        NUM7 = new javax.swing.JLabel();
        resta = new javax.swing.JLabel();
        borrartodo = new javax.swing.JLabel();
        NUM5 = new javax.swing.JLabel();
        multiplicacion = new javax.swing.JLabel();
        NUM8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        NUM2.setBackground(new java.awt.Color(43, 39, 39));
        NUM2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NUM2.setText("2");
        NUM2.setBorder(new javax.swing.border.MatteBorder(null));
        NUM2.setOpaque(true);
        NUM2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NUM2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NUM2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NUM2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NUM2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NUM2MouseReleased(evt);
            }
        });

        NUM6.setBackground(new java.awt.Color(43, 39, 39));
        NUM6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NUM6.setText("6");
        NUM6.setBorder(new javax.swing.border.MatteBorder(null));
        NUM6.setOpaque(true);
        NUM6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NUM6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NUM6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NUM6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NUM6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NUM6MouseReleased(evt);
            }
        });

        NUM9.setBackground(new java.awt.Color(43, 39, 39));
        NUM9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NUM9.setText("9");
        NUM9.setBorder(new javax.swing.border.MatteBorder(null));
        NUM9.setOpaque(true);
        NUM9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NUM9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NUM9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NUM9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NUM9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NUM9MouseReleased(evt);
            }
        });

        NUM3.setBackground(new java.awt.Color(43, 39, 39));
        NUM3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NUM3.setText("3");
        NUM3.setBorder(new javax.swing.border.MatteBorder(null));
        NUM3.setOpaque(true);
        NUM3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NUM3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NUM3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NUM3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NUM3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NUM3MouseReleased(evt);
            }
        });

        borrar.setBackground(new java.awt.Color(43, 39, 39));
        borrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borrar.setText("CE");
        borrar.setOpaque(true);
        borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                borrarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                borrarMouseReleased(evt);
            }
        });

        pantalla.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        division.setBackground(new java.awt.Color(43, 39, 39));
        division.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        division.setText("÷");
        division.setBorder(new javax.swing.border.MatteBorder(null));
        division.setOpaque(true);
        division.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                divisionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                divisionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                divisionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                divisionMouseReleased(evt);
            }
        });

        subpantalla.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        subpantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        NUM10.setBackground(new java.awt.Color(43, 39, 39));
        NUM10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NUM10.setText("0");
        NUM10.setBorder(new javax.swing.border.MatteBorder(null));
        NUM10.setOpaque(true);
        NUM10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NUM10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NUM10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NUM10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NUM10MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NUM10MouseReleased(evt);
            }
        });

        NUM1.setBackground(new java.awt.Color(43, 39, 39));
        NUM1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NUM1.setText("1");
        NUM1.setOpaque(true);
        NUM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NUM1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NUM1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NUM1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NUM1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NUM1MouseReleased(evt);
            }
        });

        igual.setBackground(new java.awt.Color(43, 39, 39));
        igual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        igual.setText("=");
        igual.setBorder(new javax.swing.border.MatteBorder(null));
        igual.setOpaque(true);
        igual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                igualMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                igualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                igualMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                igualMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                igualMouseReleased(evt);
            }
        });

        NUM4.setBackground(new java.awt.Color(43, 39, 39));
        NUM4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NUM4.setText("4");
        NUM4.setBorder(new javax.swing.border.MatteBorder(null));
        NUM4.setOpaque(true);
        NUM4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NUM4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NUM4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NUM4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NUM4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NUM4MouseReleased(evt);
            }
        });

        suma.setBackground(new java.awt.Color(43, 39, 39));
        suma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suma.setText("+");
        suma.setBorder(new javax.swing.border.MatteBorder(null));
        suma.setOpaque(true);
        suma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sumaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sumaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sumaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sumaMouseReleased(evt);
            }
        });
        suma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sumaKeyPressed(evt);
            }
        });

        NUM7.setBackground(new java.awt.Color(43, 39, 39));
        NUM7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NUM7.setText("7");
        NUM7.setBorder(new javax.swing.border.MatteBorder(null));
        NUM7.setOpaque(true);
        NUM7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NUM7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NUM7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NUM7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NUM7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NUM7MouseReleased(evt);
            }
        });

        resta.setBackground(new java.awt.Color(43, 39, 39));
        resta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resta.setText("-");
        resta.setBorder(new javax.swing.border.MatteBorder(null));
        resta.setOpaque(true);
        resta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                restaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                restaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                restaMouseReleased(evt);
            }
        });

        borrartodo.setBackground(new java.awt.Color(43, 39, 39));
        borrartodo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borrartodo.setText("C");
        borrartodo.setOpaque(true);
        borrartodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrartodoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrartodoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrartodoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                borrartodoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                borrartodoMouseReleased(evt);
            }
        });

        NUM5.setBackground(new java.awt.Color(43, 39, 39));
        NUM5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NUM5.setText("5");
        NUM5.setBorder(new javax.swing.border.MatteBorder(null));
        NUM5.setOpaque(true);
        NUM5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NUM5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NUM5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NUM5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NUM5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NUM5MouseReleased(evt);
            }
        });

        multiplicacion.setBackground(new java.awt.Color(43, 39, 39));
        multiplicacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        multiplicacion.setText("×");
        multiplicacion.setBorder(new javax.swing.border.MatteBorder(null));
        multiplicacion.setOpaque(true);
        multiplicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplicacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                multiplicacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                multiplicacionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                multiplicacionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                multiplicacionMouseReleased(evt);
            }
        });

        NUM8.setBackground(new java.awt.Color(43, 39, 39));
        NUM8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NUM8.setText("8");
        NUM8.setBorder(new javax.swing.border.MatteBorder(null));
        NUM8.setOpaque(true);
        NUM8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NUM8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NUM8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NUM8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NUM8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NUM8MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(NUM10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(NUM7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(NUM8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(NUM9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(NUM4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(NUM5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(NUM6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(resta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(NUM1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(NUM2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(NUM3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subpantalla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(borrartodo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(subpantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NUM7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NUM8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NUM9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NUM4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NUM5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NUM6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NUM2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NUM1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NUM3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NUM10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borrartodo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void divisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionMouseClicked
        
        op.setNumero1(Integer.parseInt(pantalla.getText()));
        subpantalla.setText(pantalla.getText()+" ÷ ");
        pantalla.setText(pantalla.getText()+"÷");
        pantalla.setText("");
        division1 = 1;
    }//GEN-LAST:event_divisionMouseClicked

    private void NUM2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM2MouseClicked
        // TODO add your handling code here:
        if(pantalla.getText()== "0"){
            pantalla.setText("");
        }
        pantalla.setText(pantalla.getText()+"2");
    }//GEN-LAST:event_NUM2MouseClicked

    private void NUM3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM3MouseClicked
        // TODO add your handling code here:
        if(pantalla.getText()== "0"){
            pantalla.setText("");
        }
        pantalla.setText(pantalla.getText()+"3");
    }//GEN-LAST:event_NUM3MouseClicked

    private void NUM4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM4MouseClicked
        // TODO add your handling code here:
        if(pantalla.getText()== "0"){
            pantalla.setText("");
        }
        pantalla.setText(pantalla.getText()+"4");
    }//GEN-LAST:event_NUM4MouseClicked

    private void NUM5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM5MouseClicked
        // TODO add your handling code here:
        if(pantalla.getText()== "0"){
            pantalla.setText("");
        }
        pantalla.setText(pantalla.getText()+"5");
    }//GEN-LAST:event_NUM5MouseClicked

    private void NUM6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM6MouseClicked
        // TODO add your handling code here:
        if(pantalla.getText()== "0"){
            pantalla.setText("");
        }
        pantalla.setText(pantalla.getText()+"6");
    }//GEN-LAST:event_NUM6MouseClicked

    private void NUM7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM7MouseClicked
        // TODO add your handling code here:
        if(pantalla.getText()== "0"){
            pantalla.setText("");
        }
        pantalla.setText(pantalla.getText()+"7");
    }//GEN-LAST:event_NUM7MouseClicked

    private void NUM8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM8MouseClicked
        // TODO add your handling code here:
        if(pantalla.getText()== "0"){
            pantalla.setText("");
        }
        pantalla.setText(pantalla.getText()+"8");
    }//GEN-LAST:event_NUM8MouseClicked

    private void NUM9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM9MouseClicked
        // TODO add your handling code here:
        if(pantalla.getText()== "0"){
            pantalla.setText("");
        }
        pantalla.setText(pantalla.getText()+"9");
    }//GEN-LAST:event_NUM9MouseClicked

    private void NUM10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM10MouseClicked
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText()+"0");
    }//GEN-LAST:event_NUM10MouseClicked

    private void igualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igualMouseClicked
        // TODO add your handling code here:
        if(pantalla.getText().equals("0")){
            pantalla.setText("aiuda");
            subpantalla.setText("");
            op.setNumero1(0);
            op.setNumero2(0);
        }
        op.setNumero2(Integer.parseInt(pantalla.getText()));
        if(suma1 == 1){
            subpantalla.setText(subpantalla.getText()+ pantalla.getText());
        }
        if(resta1 == 1){
           subpantalla.setText(subpantalla.getText()+ pantalla.getText());
        }
        if(multiplicacion1 == 1){
            subpantalla.setText(subpantalla.getText()+ pantalla.getText());
        }
        if(division1 == 1){
            subpantalla.setText(subpantalla.getText()+ pantalla.getText());
        }
        pantalla.setText(pantalla.getText()+"=");
        pantalla.setText("");
        if(suma1 == 1){
            pantalla.setText(String.valueOf(op.suma()));
            suma1 = 0;
        }
        if(resta1 == 1){
            pantalla.setText(String.valueOf(op.resta()));
            resta1 = 0;
        }
        if(multiplicacion1 == 1){
            pantalla.setText(String.valueOf(op.multiplicacion()));
            multiplicacion1 = 0;
        }
        if(division1 == 1){
            pantalla.setText(String.valueOf(op.division()));
            division1 = 0;
        }
          
        
    }//GEN-LAST:event_igualMouseClicked

    private void sumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumaMouseClicked
        // TODO add your handling code here:
        suma1 = 1;
        op.setNumero1(Integer.parseInt(pantalla.getText()));
        subpantalla.setText(pantalla.getText()+" + ");
        pantalla.setText(pantalla.getText()+"+");
        pantalla.setText("");
    }//GEN-LAST:event_sumaMouseClicked

    private void restaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaMouseClicked
        // TODO add your handling code here:
        op.setNumero1(Integer.parseInt(pantalla.getText()));
        subpantalla.setText(pantalla.getText()+" - ");
        pantalla.setText(pantalla.getText()+"-");
        pantalla.setText("");
        resta1 = 1;
    }//GEN-LAST:event_restaMouseClicked

    private void multiplicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicacionMouseClicked
        // TODO add your handling code here:
        op.setNumero1(Integer.parseInt(pantalla.getText()));
        subpantalla.setText(pantalla.getText()+" × ");
        pantalla.setText(pantalla.getText()+"×");
        pantalla.setText("");
        multiplicacion1 = 1;
    }//GEN-LAST:event_multiplicacionMouseClicked

    private void sumaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sumaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumaKeyPressed

    private void borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarMouseClicked
        // TODO add your handling code here:
        pantalla.setText(pantalla.getText().substring(0, pantalla.getText().length()-1));
        if(pantalla.getText().length()== 0){
            pantalla.setText("0");
        }
    }//GEN-LAST:event_borrarMouseClicked

    private void borrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarMouseEntered
        // TODO add your handling code here:
        borrar.setBackground(new Color(254,174,37));
    }//GEN-LAST:event_borrarMouseEntered

    private void borrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarMouseExited
        // TODO add your handling code here:
        borrar.setBackground(new Color(43,39,39));
    }//GEN-LAST:event_borrarMouseExited

    private void borrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarMousePressed
        // TODO add your handling code here:
        borrar.setBackground(new Color(254,202,114));
    }//GEN-LAST:event_borrarMousePressed

    private void borrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarMouseReleased
        // TODO add your handling code here:
        borrar.setBackground(new Color(247,184,98));
        if(borrar.getX()>getWidth()||borrar.getY()>getWidth()){
            borrar.setBackground(new Color(43,39,39));
        }
        if(borrar.getX()<0||borrar.getY()<0){
            borrar.setBackground(new Color(43,39,39));
        }
        borrar.repaint();
    }//GEN-LAST:event_borrarMouseReleased

    private void NUM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM1MouseClicked
        // TODO add your handling code here:
        if(pantalla.getText()== "0"){
            pantalla.setText("");
        }
        pantalla.setText(pantalla.getText()+"1");
        
        
    }//GEN-LAST:event_NUM1MouseClicked

    private void NUM1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM1MouseEntered
        // TODO add your handling code here:
        NUM1.setBackground(new Color(71,68,68));
    }//GEN-LAST:event_NUM1MouseEntered

    private void NUM1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM1MouseExited
        // TODO add your handling code here:
        NUM1.setBackground(new Color(43,39,39));
    }//GEN-LAST:event_NUM1MouseExited

    private void NUM1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM1MousePressed
        // TODO add your handling code here:
        NUM1.setBackground(new Color(103,101,101));
    }//GEN-LAST:event_NUM1MousePressed

    private void NUM1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM1MouseReleased
        // TODO add your handling code here:
        NUM1.setBackground(new Color(71,68,68));
        if(NUM1.getX()>getWidth()||NUM1.getY()>getWidth()){
            NUM1.setBackground(new Color(43,39,39));
        }
        if(NUM1.getX()<0||NUM1.getY()<0){
            NUM1.setBackground(new Color(43,39,39));
        }
        NUM1.repaint();
    }//GEN-LAST:event_NUM1MouseReleased

    private void NUM2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM2MouseEntered
        // TODO add your handling code here:
        NUM2.setBackground(new Color(71,68,68));
    }//GEN-LAST:event_NUM2MouseEntered

    private void NUM2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM2MouseExited
        // TODO add your handling code here:
        NUM2.setBackground(new Color(43,39,39));
    }//GEN-LAST:event_NUM2MouseExited

    private void NUM2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM2MousePressed
        // TODO add your handling code here:
        NUM2.setBackground(new Color(103,101,101));
    }//GEN-LAST:event_NUM2MousePressed

    private void NUM2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM2MouseReleased
        // TODO add your handling code here:
        NUM2.setBackground(new Color(71,68,68));
        if(NUM2.getX()>getWidth()||NUM2.getY()>getWidth()){
            NUM2.setBackground(new Color(43,39,39));
        }
        if(NUM2.getX()<0||NUM2.getY()<0){
            NUM2.setBackground(new Color(43,39,39));
        }
        NUM2.repaint();
    }//GEN-LAST:event_NUM2MouseReleased

    private void NUM3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM3MouseEntered
        // TODO add your handling code here:
        NUM3.setBackground(new Color(71,68,68));
    }//GEN-LAST:event_NUM3MouseEntered

    private void NUM3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM3MouseExited
        // TODO add your handling code here:
        NUM3.setBackground(new Color(43,39,39));
    }//GEN-LAST:event_NUM3MouseExited

    private void NUM3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM3MousePressed
        // TODO add your handling code here:
        NUM3.setBackground(new Color(103,101,101));
    }//GEN-LAST:event_NUM3MousePressed

    private void NUM3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM3MouseReleased
        // TODO add your handling code here:
        NUM3.setBackground(new Color(71,68,68));
        if(NUM3.getX()>getWidth()||NUM3.getY()>getWidth()){
            NUM3.setBackground(new Color(43,39,39));
        }
        if(NUM3.getX()<0||NUM3.getY()<0){
            NUM3.setBackground(new Color(43,39,39));
        }
        NUM3.repaint();
    }//GEN-LAST:event_NUM3MouseReleased

    private void NUM10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM10MouseEntered
        // TODO add your handling code here:
        NUM10.setBackground(new Color(71,68,68));
    }//GEN-LAST:event_NUM10MouseEntered

    private void NUM10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM10MouseExited
        // TODO add your handling code here:
        NUM10.setBackground(new Color(43,39,39));
    }//GEN-LAST:event_NUM10MouseExited

    private void NUM10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM10MousePressed
        // TODO add your handling code here:
        NUM10.setBackground(new Color(103,101,101));
    }//GEN-LAST:event_NUM10MousePressed

    private void NUM10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM10MouseReleased
        // TODO add your handling code here:
        NUM10.setBackground(new Color(71,68,68));
        if(NUM10.getX()>getWidth()||NUM10.getY()>getWidth()){
            NUM10.setBackground(new Color(43,39,39));
        }
        if(NUM10.getX()<0||NUM10.getY()<0){
            NUM10.setBackground(new Color(43,39,39));
        }
        NUM10.repaint();
    }//GEN-LAST:event_NUM10MouseReleased

    private void NUM4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM4MouseEntered
        // TODO add your handling code here:
        NUM4.setBackground(new Color(71,68,68));
    }//GEN-LAST:event_NUM4MouseEntered

    private void NUM4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM4MouseExited
        // TODO add your handling code here:
        NUM4.setBackground(new Color(43,39,39));
    }//GEN-LAST:event_NUM4MouseExited

    private void NUM4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM4MousePressed
        // TODO add your handling code here:
        NUM4.setBackground(new Color(103,101,101));
    }//GEN-LAST:event_NUM4MousePressed

    private void NUM4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM4MouseReleased
        // TODO add your handling code here:
        NUM4.setBackground(new Color(71,68,68));
        if(NUM4.getX()>getWidth()||NUM4.getY()>getWidth()){
            NUM4.setBackground(new Color(43,39,39));
        }
        if(NUM4.getX()<0||NUM4.getY()<0){
            NUM4.setBackground(new Color(43,39,39));
        }
        NUM4.repaint();
    }//GEN-LAST:event_NUM4MouseReleased

    private void NUM5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM5MouseEntered
        // TODO add your handling code here:
        NUM5.setBackground(new Color(71,68,68));
    }//GEN-LAST:event_NUM5MouseEntered

    private void NUM5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM5MouseExited
        // TODO add your handling code here:
        NUM5.setBackground(new Color(43,39,39));
    }//GEN-LAST:event_NUM5MouseExited

    private void NUM5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM5MousePressed
        // TODO add your handling code here:
        NUM5.setBackground(new Color(103,101,101));
    }//GEN-LAST:event_NUM5MousePressed

    private void NUM5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM5MouseReleased
        // TODO add your handling code here:
        NUM5.setBackground(new Color(71,68,68));
        if(NUM5.getX()>getWidth()||NUM5.getY()>getWidth()){
            NUM5.setBackground(new Color(43,39,39));
        }
        if(NUM5.getX()<0||NUM5.getY()<0){
            NUM5.setBackground(new Color(43,39,39));
        }
        NUM5.repaint();
    }//GEN-LAST:event_NUM5MouseReleased

    private void NUM6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM6MouseEntered
        // TODO add your handling code here:
        NUM6.setBackground(new Color(71,68,68));
    }//GEN-LAST:event_NUM6MouseEntered

    private void NUM6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM6MouseExited
        // TODO add your handling code here:
        NUM6.setBackground(new Color(43,39,39));
    }//GEN-LAST:event_NUM6MouseExited

    private void NUM6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM6MousePressed
        NUM6.setBackground(new Color(103,101,101));
    }//GEN-LAST:event_NUM6MousePressed

    private void NUM6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM6MouseReleased
        // TODO add your handling code here:
        NUM6.setBackground(new Color(71,68,68));
        if(NUM6.getX()>getWidth()||NUM6.getY()>getWidth()){
            NUM6.setBackground(new Color(43,39,39));
        }
        if(NUM6.getX()<0||NUM6.getY()<0){
            NUM6.setBackground(new Color(43,39,39));
        }
        NUM6.repaint();
    }//GEN-LAST:event_NUM6MouseReleased

    private void NUM7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM7MouseEntered
        // TODO add your handling code here:
        NUM7.setBackground(new Color(71,68,68));
    }//GEN-LAST:event_NUM7MouseEntered

    private void NUM7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM7MouseExited
        // TODO add your handling code here:
        NUM7.setBackground(new Color(43,39,39));
    }//GEN-LAST:event_NUM7MouseExited

    private void NUM7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM7MousePressed
        // TODO add your handling code here:
        NUM7.setBackground(new Color(103,101,101));
    }//GEN-LAST:event_NUM7MousePressed

    private void NUM7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM7MouseReleased
        // TODO add your handling code here:
        NUM7.setBackground(new Color(71,68,68));
        if(NUM7.getX()>getWidth()||NUM7.getY()>getWidth()){
            NUM7.setBackground(new Color(43,39,39));
        }
        if(NUM7.getX()<0||NUM7.getY()<0){
            NUM7.setBackground(new Color(43,39,39));
        }
        NUM7.repaint();
    }//GEN-LAST:event_NUM7MouseReleased

    private void NUM8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM8MouseEntered
        // TODO add your handling code here:
        NUM8.setBackground(new Color(71,68,68));
    }//GEN-LAST:event_NUM8MouseEntered

    private void NUM8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM8MouseExited
        // TODO add your handling code here:
        NUM8.setBackground(new Color(43,39,39));
    }//GEN-LAST:event_NUM8MouseExited

    private void NUM8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM8MousePressed
        // TODO add your handling code here:
        NUM8.setBackground(new Color(103,101,101));
    }//GEN-LAST:event_NUM8MousePressed

    private void NUM8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM8MouseReleased
        // TODO add your handling code here:
        NUM8.setBackground(new Color(71,68,68));
        if(NUM8.getX()>getWidth()||NUM8.getY()>getWidth()){
            NUM8.setBackground(new Color(43,39,39));
        }
        if(NUM8.getX()<0||NUM8.getY()<0){
            NUM8.setBackground(new Color(43,39,39));
        }
        NUM8.repaint();
    }//GEN-LAST:event_NUM8MouseReleased

    private void NUM9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM9MouseEntered
        // TODO add your handling code here:
        NUM9.setBackground(new Color(71,68,68));
    }//GEN-LAST:event_NUM9MouseEntered

    private void NUM9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM9MouseExited
        // TODO add your handling code here:
        NUM9.setBackground(new Color(43,39,39));
    }//GEN-LAST:event_NUM9MouseExited

    private void NUM9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM9MousePressed
        // TODO add your handling code here:
        NUM9.setBackground(new Color(103,101,101));
    }//GEN-LAST:event_NUM9MousePressed

    private void NUM9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM9MouseReleased
        // TODO add your handling code here:
        NUM9.setBackground(new Color(71,68,68));
        if(NUM9.getX()>getWidth()||NUM9.getY()>getWidth()){
            NUM9.setBackground(new Color(43,39,39));
        }
        if(NUM9.getX()<0||NUM9.getY()<0){
            NUM9.setBackground(new Color(43,39,39));
        }
        NUM9.repaint();
    }//GEN-LAST:event_NUM9MouseReleased

    private void igualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igualMouseEntered
        // TODO add your handling code here:
        igual.setBackground(new Color(254,174,37));
    }//GEN-LAST:event_igualMouseEntered

    private void igualMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igualMousePressed
        // TODO add your handling code here:
        igual.setBackground(new Color(254,202,114));
    }//GEN-LAST:event_igualMousePressed

    private void igualMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igualMouseReleased
        // TODO add your handling code here:
        igual.setBackground(new Color(247,184,98));
        if(igual.getX()>getWidth()||igual.getY()>getWidth()){
            igual.setBackground(new Color(43,39,39));
        }
        if(igual.getX()<0||igual.getY()<0){
            igual.setBackground(new Color(43,39,39));
        }
        igual.repaint();
    }//GEN-LAST:event_igualMouseReleased

    private void multiplicacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicacionMouseEntered
        // TODO add your handling code here:}
        multiplicacion.setBackground(new Color(254,174,37));
    }//GEN-LAST:event_multiplicacionMouseEntered

    private void multiplicacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicacionMousePressed
        // TODO add your handling code here:
        multiplicacion.setBackground(new Color(254,174,37));
    }//GEN-LAST:event_multiplicacionMousePressed

    private void multiplicacionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicacionMouseReleased
        // TODO add your handling code here:}
        multiplicacion.setBackground(new Color(247,184,98));
        if(multiplicacion.getX()>getWidth()||igual.getY()>getWidth()){
            multiplicacion.setBackground(new Color(43,39,39));
        }
        if(multiplicacion.getX()<0||multiplicacion.getY()<0){
            multiplicacion.setBackground(new Color(43,39,39));
        }
        multiplicacion.repaint();
    }//GEN-LAST:event_multiplicacionMouseReleased

    private void igualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igualMouseExited
        // TODO add your handling code here:
        igual.setBackground(new Color(43,39,39));
    }//GEN-LAST:event_igualMouseExited

    private void multiplicacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicacionMouseExited
        // TODO add your handling code here:
        multiplicacion.setBackground(new Color(43,39,39));
    }//GEN-LAST:event_multiplicacionMouseExited

    private void divisionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionMouseEntered
        // TODO add your handling code here:
        division.setBackground(new Color(254,174,37));
    }//GEN-LAST:event_divisionMouseEntered

    private void divisionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionMouseExited
        // TODO add your handling code here:
        division.setBackground(new Color(43,39,39));
    }//GEN-LAST:event_divisionMouseExited

    private void divisionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionMousePressed
        // TODO add your handling code here:
        division.setBackground(new Color(254,174,37));
    }//GEN-LAST:event_divisionMousePressed

    private void divisionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionMouseReleased
        // TODO add your handling code here:
        division.setBackground(new Color(247,184,98));
        if(division.getX()>getWidth()||division.getY()>getWidth()){
            division.setBackground(new Color(43,39,39));
        }
        if(division.getX()<0||division.getY()<0){
            division.setBackground(new Color(43,39,39));
        }
        division.repaint();
    }//GEN-LAST:event_divisionMouseReleased

    private void restaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaMouseEntered
        // TODO add your handling code here:
        resta.setBackground(new Color(254,174,37));
    }//GEN-LAST:event_restaMouseEntered

    private void restaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaMouseExited
        // TODO add your handling code here:
        resta.setBackground(new Color(43,39,39));
    }//GEN-LAST:event_restaMouseExited

    private void restaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaMousePressed
        // TODO add your handling code here:
        resta.setBackground(new Color(254,174,37));
    }//GEN-LAST:event_restaMousePressed

    private void restaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaMouseReleased
        // TODO add your handling code here:
        resta.setBackground(new Color(247,184,98));
        if(resta.getX()>getWidth()||resta.getY()>getWidth()){
            resta.setBackground(new Color(43,39,39));
        }
        if(resta.getX()<0||resta.getY()<0){
            resta.setBackground(new Color(43,39,39));
        }
        resta.repaint();
    }//GEN-LAST:event_restaMouseReleased

    private void sumaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumaMouseEntered
        // TODO add your handling code here:
        suma.setBackground(new Color(254,174,37));
    }//GEN-LAST:event_sumaMouseEntered

    private void sumaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumaMouseExited
        // TODO add your handling code here:
        suma.setBackground(new Color(43,39,39));
    }//GEN-LAST:event_sumaMouseExited

    private void sumaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumaMousePressed
        // TODO add your handling code here:
        suma.setBackground(new Color(254,174,37));
    }//GEN-LAST:event_sumaMousePressed

    private void sumaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumaMouseReleased
        // TODO add your handling code here:
        suma.setBackground(new Color(247,184,98));
        if(suma.getX()>getWidth()||suma.getY()>getWidth()){
            suma.setBackground(new Color(43,39,39));
        }
        if(suma.getX()<0||suma.getY()<0){
            suma.setBackground(new Color(43,39,39));
        }
        suma.repaint();
    }//GEN-LAST:event_sumaMouseReleased

    private void borrartodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrartodoMouseClicked
        // TODO add your handling code here:
        pantalla.setText("");
        subpantalla.setText("");
        op.setNumero1(0);
        op.setNumero2(0);
        if(pantalla.getText().length()== 0){
            pantalla.setText("0");
        }
        if(subpantalla.getText().length()== 0){
            subpantalla.setText("0");
        }
    }//GEN-LAST:event_borrartodoMouseClicked

    private void borrartodoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrartodoMouseEntered
        // TODO add your handling code here:
        borrartodo.setBackground(new Color(254,174,37));
    }//GEN-LAST:event_borrartodoMouseEntered

    private void borrartodoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrartodoMouseExited
        // TODO add your handling code here:
        borrartodo.setBackground(new Color(43,39,39));
    }//GEN-LAST:event_borrartodoMouseExited

    private void borrartodoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrartodoMousePressed
        // TODO add your handling code here:
        borrartodo.setBackground(new Color(254,174,37));
    }//GEN-LAST:event_borrartodoMousePressed

    private void borrartodoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrartodoMouseReleased
        // TODO add your handling code here:
        borrartodo.setBackground(new Color(247,184,98));
        if(borrartodo.getX()>getWidth()||borrartodo.getY()>getWidth()){
            borrartodo.setBackground(new Color(43,39,39));
        }
        if(borrartodo.getX()<0||borrartodo.getY()<0){
            borrartodo.setBackground(new Color(43,39,39));
        }
        borrartodo.repaint();
    }//GEN-LAST:event_borrartodoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NUM1;
    private javax.swing.JLabel NUM10;
    private javax.swing.JLabel NUM2;
    private javax.swing.JLabel NUM3;
    private javax.swing.JLabel NUM4;
    private javax.swing.JLabel NUM5;
    private javax.swing.JLabel NUM6;
    private javax.swing.JLabel NUM7;
    private javax.swing.JLabel NUM8;
    private javax.swing.JLabel NUM9;
    private javax.swing.JLabel borrar;
    private javax.swing.JLabel borrartodo;
    private javax.swing.JLabel division;
    private javax.swing.JLabel igual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel multiplicacion;
    private javax.swing.JLabel pantalla;
    private javax.swing.JLabel resta;
    private javax.swing.JLabel subpantalla;
    private javax.swing.JLabel suma;
    // End of variables declaration//GEN-END:variables
}
